### ISSUE TITLE
Crash with installation on empty VM

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#31]
Following the instructions on a clean VM running Ubuntu LTS 14.04 as described in https://github.com/splay-project/splay/blob/master/INSTALL.md, everything goes smoothly. 

Then, trying to execute a simple RPC server: 
```lua
require"splay.base"
local rpc         = require"splay.rpcq"      -- for RPCs
function main()
    rpc.server(30000)
end
events.run(main())
```

The following error occurs:
```lua
lua: /home/ubuntu/local/lualibs/lib/splay/net.lua:158: attempt to call field 'bind' (a nil value)
stack traceback:
	/home/ubuntu/local/lualibs/lib/splay/net.lua:158: in function </home/ubuntu/local/lualibs/lib/splay/net.lua:137>
	(tail call): ?
	test_bind.lua:12: in function 'main'
	test_bind.lua:15: in main chunk
	[C]: ?
```

**Comment by vschiavoni** [comment]
Same problem with simple rpc:
```lua
require"splay.base"
local rpc         = require"splay.rpc"      -- for RPCs
function main()
    rpc.server(30000)
end
events.run(main())
```

**Comment by vschiavoni** [comment]
Even simpler test-case with splay.net:

```lua
require("splay.base")
net = require("splay.net")
function echo_server(s)
end
net.server(30000, echo_server)
events.run()
```

Error:
```lua
lua: /home/ubuntu/local/lualibs/lib/splay/net.lua:158: attempt to call field 'bind' (a nil value)
stack traceback:
	/home/ubuntu/local/lualibs/lib/splay/net.lua:158: in function 'server'
	test_net.lua:5: in main chunk
	[C]: ?
```

**Comment by leuchtkaefer** [comment]
Hi Valerio, 
I tried to install splay in my laptop (on ubuntu VM) and does not work. The error is identical to the issue below (your e-mail). I cannot find the source of the problem. The installation I did 1-2 weeks ago on my lab desktop worked but now following the instructions, the installation crashes. Any ideas? Did you change sth in the installer? Best Verónica


     On Thursday, May 28, 2015 3:57 PM, Valerio Schiavoni <notifications@github.com> wrote:
   
 

 Following the instructions on a clean VM as described in https://github.com/splay-project/splay/blob/master/INSTALL.md, everything goes smoothly. 
Then, trying to execute a simple tcp-server: require"splay.base"
local rpc         = require"splay.rpcq"      -- for RPCs
function main()
    rpc.server(30000)
end
events.run(main())The following error occurs:lua: /home/ubuntu/local/lualibs/lib/splay/net.lua:158: attempt to call field 'bind' (a nil value)
stack traceback:
    /home/ubuntu/local/lualibs/lib/splay/net.lua:158: in function </home/ubuntu/local/lualibs/lib/splay/net.lua:137>
    (tail call): ?
    test_bind.lua:12: in function 'main'
    test_bind.lua:15: in main chunk
    [C]: ?—

**Comment by vschiavoni** [comment]
The issue is still open, still investigating. We did not change code in the master branch. 
Can it be due to a change in the dependencies installed in ubuntu ? Which versions of the packages were installed in your case ?

**Comment by vschiavoni** [comment]
Post-mortem analysis: the issue was due to the default installed LuaSocket version. Ubuntu 14.04 LTS now ships by default LuaSocket 3.0-RC, which ships its own socket.connect function. Therefore, the wrap (..) function was skipping most of its body, thus do not adding.
